spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: whrwhr
    url: jdbc:mysql://localhost:3306/products?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    template-loader-path:
    - classpath:/templates/  
server:
  context-path: /AgriculturalProducts
  